[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "nft"

# Headers for CORS and security
[[headers]]
  for = "/*"
  [headers.values]
    # CORS headers
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control
    Cache-Control = "public, max-age=3600"

# Special headers for function endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "no-cache"

# Redirects for API endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Environment variables (example - actual values set in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
